app = "pizzariadocarlos"
primary_region = "ewr"

[build]
  builder = "Dockerfile"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    restart_limit = 0
